version: "3.9"

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --sql-mode=""
    environment:
      MYSQL_DATABASE: tms
      MYSQL_USER: tms
      MYSQL_PASSWORD: tms
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    image: tms-backend:latest
    volumes:
      - ./backend:/var/www/html
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: "1"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

  frontend:
    image: node:lts
    working_dir: /app
    command: sh -c "if [ -f package.json ]; then npm run dev -- --host 0.0.0.0; else tail -f /dev/null; fi"
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app

volumes:
  dbdata:


